def build(ctx):
  def injectpath(task):
    import re
    src = task.inputs[0].abspath()
    tgt = task.outputs[0].abspath() 
    f=open(src)
    txt = f.read()
    txt = re.sub("\$REPLACEPATH",ctx.env.PYTHONDIR,txt)
    f=open(tgt,"w")
    print >>f,txt,
    f.close()
    
  ctx.load("execconfig","waf_tools")
  if ctx.env.CYTHON:
    ctx(
      features = "c cshlib pyext",
      source = "clik/lkl.pyx",
      target  = "lkl",
      includes = "../src",
      use = "clik",
      install_path = "${PYTHONDIR}/clik"
    )
  
  ctx(
    source = "clik/parobject.py clik/__init__.py",
    install_path = "${PYTHONDIR}/clik"
  )
  
  ctx(
    execrule = injectpath,
    source = "synthetic_smica.py",
    target = "synthetic_smica",
    install_path = ctx.env.BINDIR
    )    
  ctx(
    execrule = injectpath,
    source = "clik_example_py.py",
    target = "clik_example_py",
    install_path = ctx.env.BINDIR
    )    
  

