import execconfig as excc
import os.path as osp

def build(bld):
  
  source_clik = 'aplowly.c erfinv.c fowly.c clik.c lklbs.c lowly.c lowly_common.c lowly_pol.c smica.c clik_helper.c clik_hfipack.c'.split()
  source_clik += ['clik_bopix.c']*(bld.options.no_bopix==False)
  source_clik += [osp.join("minipmc", src) for src in 'errorlist.c io.c distribution.c'.split()]*( not bld.env.has_pmc)
  source_clik = [src for src in source_clik if src]
  
  uselib_clik = [ff for ff in ('hdf5 chealpix lapack pmc gsl dl' ).split() if ff]
  
  bld.shlib(
    source   = source_clik,
    target   = 'clik', 
    includes = '.'+" minipmc/"*(not bld.env.has_pmc),
    uselib   = uselib_clik,
    use = "mybopix"* (bld.options.no_bopix==False),
    cflags = "-fopenmp"
    )
  bld.install_files('${PREFIX}/include/', 
                    'clik.h minipmc/pmc.h minipmc/io.h minipmc/errorlist.h')

  pmclinkline = " ".join([excc.bld_link_line(bld,nn) for nn in uselib_clik])
  pmclinkline += " "+bld.env.LIBPATH_ST%bld.env.LIBDIR+" "+bld.env.RPATH_ST%bld.env.LIBDIR+" "+" ".join([bld.env.LIB_ST%l for l in ("clik",)])
  pmcincline = " ".join([excc.bld_inc_line(bld,nn) for nn in uselib_clik])
  pmcincline += ' '+excc.mkstr(bld.env.CPPPATH_ST,[bld.env.PREFIX+"/include"])
  pmcdefline = " ".join([excc.bld_def_line(bld,nn) for nn in uselib_clik])
  
  bld.load("execconfig","waf_tools")  
  bld(execrule=excc.createconfig(pmclinkline,pmcincline,pmcdefline), target="clik-config", install_path='${BINDIR}')

  # Fortran
  if not bld.options.no_bopix:
    bld(
      features = 'fc cshlib',
      source = 'bopix.F90 library.F90 parameter_module.F90 read_parameter.F90 simple_parser.F90 clik_bopix.f90',
      target = 'mybopix',
      uselib = 'healpix_f90 pmc lapack gsl fc_omp fc_runtime fcshlib',
      )
  
  bld.stlib(
    source = 'clik_fortran.c clik.f90',
    target = 'clik_f90',
    includes = '.'+" minipmc/"*(not bld.env.has_pmc),
    use = 'clik'
    )
    
  pmclinkline += " "+bld.env.LIBPATH_ST%bld.env.LIBDIR+" "+bld.env.RPATH_ST%bld.env.LIBDIR+" "+" ".join([bld.env.LIB_ST%l for l in ("clik_f90",)])    
  bld(execrule=excc.createconfig(pmclinkline,pmcincline,pmcdefline), target="clik_f90-config", install_path='${BINDIR}')

  bld(
    features = 'fc fcprogram',
    source = 'clik_example_f90.f90',
    includes = '.',
    target = 'clik_example_f90',
    use = 'clik_f90'
  )

  bld(
    features = 'c cprogram',
    source = 'clik_example_c.c',
    target = 'clik_example_C',
    use = 'clik',
    includes = '.'+" minipmc/"*(not bld.env.has_pmc)
  )